apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel
spec:
  serviceName: sentinel
  replicas: 3
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      initContainers:
      - name: config
        image: valkey/valkey:latest
        command: [ "sh", "-c" ]
        args:
          - |
            nodes=valkey-0.valkey,valkey-1.valkey,valkey-2.valkey
            loop=$(echo $nodes | sed -e "s/,/\n/g")

            for i in $loop
            do
                echo "finding master at $i"
                MASTER=$(valkey-cli --no-auth-warning --raw -h $i  info replication | awk '{print $1}' | grep master_host: | cut -d ":" -f2)
                if [ "$MASTER" = "" ]; then
                    echo "no master found"
                    MASTER=
                else
                    echo "found $MASTER"
                    break
                fi
            done
            echo "sentinel monitor mymaster $MASTER 6379 2" >> /tmp/master
            echo "port 5000
            sentinel resolve-hostnames yes
            sentinel announce-hostnames yes
            $(cat /tmp/master)
            sentinel down-after-milliseconds mymaster 500
            sentinel failover-timeout mymaster 500
            sentinel parallel-syncs mymaster 1
            " > /etc/valkey/sentinel.conf
            cat /etc/valkey/sentinel.conf
        volumeMounts:
        - name: valkey-config
          mountPath: /etc/valkey/
      containers:
      - name: sentinel
        image: valkey/valkey:latest
        command: ["valkey-sentinel"]
        args: ["/etc/valkey/sentinel.conf"]
        ports:
        - containerPort: 5000
          name: sentinel
        volumeMounts:
        - name: valkey-config
          mountPath: /etc/valkey/
      volumes:
      - name: valkey-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel
spec:
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    name: sentinel
  selector:
    app: sentinel